// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type History struct {
	ID       int32              `json:"id"`
	Type     string             `json:"type"`
	TypeID   int32              `json:"type_id"`
	OldValue json.RawMessage    `json:"old_value"`
	Value    json.RawMessage    `json:"value"`
	Date     pgtype.Timestamptz `json:"date"`
	UserID   string             `json:"user_id"`
	OrderID  pgtype.UUID        `json:"order_id"`
}

type Order struct {
	ID          pgtype.UUID        `json:"id"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	City        string             `json:"city"`
	Subdivision pgtype.Text        `json:"subdivision"`
	Price       pgtype.Numeric     `json:"price"`
	Platform    string             `json:"platform"`
	GeneralID   pgtype.UUID        `json:"general_id"`
	OrderNumber pgtype.Text        `json:"order_number"`
	Executor    pgtype.Text        `json:"executor"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID            int32              `json:"id"`
	ProductID     string             `json:"product_id"`
	ExternalID    pgtype.Text        `json:"external_id"`
	Status        string             `json:"status"`
	BasePrice     pgtype.Numeric     `json:"base_price"`
	Price         pgtype.Numeric     `json:"price"`
	EarnedBonuses pgtype.Numeric     `json:"earned_bonuses"`
	SpentBonuses  pgtype.Numeric     `json:"spent_bonuses"`
	Gift          pgtype.Bool        `json:"gift"`
	OwnerID       pgtype.Text        `json:"owner_id"`
	DeliveryID    pgtype.Text        `json:"delivery_id"`
	ShopAssistant pgtype.Text        `json:"shop_assistant"`
	Warehouse     pgtype.Text        `json:"warehouse"`
	OrderID       pgtype.UUID        `json:"order_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       json.RawMessage    `json:"payload"`
	Status        string             `json:"status"`
	RetryCount    pgtype.Int4        `json:"retry_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
}

type Payment struct {
	ID             pgtype.UUID        `json:"id"`
	OrderID        pgtype.UUID        `json:"order_id"`
	Type           string             `json:"type"`
	Sum            pgtype.Numeric     `json:"sum"`
	Payed          pgtype.Bool        `json:"payed"`
	Info           pgtype.Text        `json:"info"`
	ContractNumber pgtype.Text        `json:"contract_number"`
	CreditData     json.RawMessage    `json:"credit_data"`
	ExternalID     pgtype.Text        `json:"external_id"`
	CardData       json.RawMessage    `json:"card_data"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
