// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateHistory(ctx context.Context, arg CreateHistoryParams) (History, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	DeleteHistory(ctx context.Context, id int32) error
	DeleteOrder(ctx context.Context, id uuid.UUID) error
	DeleteOrderItem(ctx context.Context, id uuid.UUID) error
	DeleteOutboxEvent(ctx context.Context, id uuid.UUID) error
	DeletePayment(ctx context.Context, id uuid.UUID) error
	GetHistory(ctx context.Context, id int32) (History, error)
	GetOrder(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderItem(ctx context.Context, id uuid.UUID) (OrderItem, error)
	GetOutboxEvent(ctx context.Context, id uuid.UUID) (OutboxEvent, error)
	GetPayment(ctx context.Context, id uuid.UUID) (Payment, error)
	UpdateHistory(ctx context.Context, arg UpdateHistoryParams) (History, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error)
	UpdateOutboxEvent(ctx context.Context, arg UpdateOutboxEventParams) (OutboxEvent, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
